---
title: "Well Being Survey"
author: "Naomi Liftman"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r message = FALSE, warning = FALSE, error = FALSE}
# loading the necessary libraries
library(tidyverse)
library(ggplot2)
library(rio)
library(stringr)
```

# First Section

```{r}
#pulling the data and renaming the first section
survey_hopefully <- import("well_being_survey.xlsx") %>% 
  rename("large_enrollment" = 7,
         "update_tech_hybrid" = 8,
         "mentoring" = 9,
         "three_year" = 10,
         "teaching_evals_replace" = 11,
         "course_release_national_level_service" = 12,
         "incentives_mentoring" = 13,
         "distribute_workloads" = 14)
  
# just the first section data
first_section <- survey_hopefully %>% 
  select(ID, large_enrollment:distribute_workloads)

#remove the rows that have nonsense (they have no ID, but I cann
first_section <- first_section %>% 
  drop_na(ID)

```

# Removing all Characters and Converting to Numeric for Large Enrollment
```{r}
#removing highest and lowest from each of the sections so we can convert to numeric
#large_enrollment
#replacing the NA's with the lowest!
first_section[is.na(first_section)] <- 6

#removing all the blank spaces on both sides of the string
first_section$large_enrollment <- str_trim(first_section$large_enrollment, side = c("both"))

#removing the strings and replacing them with numbers
first_section$large_enrollment <- sub("1 - Highest", 1, first_section$large_enrollment)
first_section$large_enrollment <- sub("5 - Lowest", 5, first_section$large_enrollment)

#turning it all to numeric
first_section$large_enrollment <- as.numeric(first_section$large_enrollment)

#count df
rehee <- first_section %>% 
  count(large_enrollment)
```




```{r}
#update_tech_hybrid
first_section$update_tech_hybrid <- sub("1 - Highest", 1, first_section$update_tech_hybrid)
first_section$update_tech_hybrid <- sub("5 - Lowest", 5, first_section$update_tech_hybrid)

#mentoring
first_section$mentoring <- sub("1 - Highest", 1, first_section$mentoring)
first_section$mentoring <- sub("5 - Lowest", 5, first_section$mentoring)

#three_year
first_section$three_year <- sub("1 - Highest", 1, first_section$three_year)
first_section$three_year <- sub("5 - Lowest", 5, first_section$three_year)

#teaching_evals_erase
first_section$teaching_evals_replace <- sub("1 - Highest", 1, first_section$teaching_evals_replace)
first_section$teaching_evals_replace <- sub("5 - Lowest", 5, first_section$teaching_evals_replace)

#course_release
first_section$course_release_national_level_service <- sub("1 - Highest", 1, first_section$course_release_national_level_service)
first_section$course_release_national_level_service <- sub("5 - Lowest", 5, first_section$course_release_national_level_service)

#incentives_monitoring
first_section$incentives_mentoring <- sub("1 - Highest", 1, first_section$incentives_mentoring)
first_section$incentives_mentoring <- sub("5 - Lowest", 5, first_section$incentives_mentoring)

#distribute workloads
first_section$distribute_workloads <- sub("1 - Highest", 1, first_section$distribute_workloads)
first_section$distribute_workloads <- sub("5 - Lowest", 5, first_section$distribute_workloads)
```

