---
title: "Modeling Well Being Survey"
author: "Naomi Liftman"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r message = FALSE, warning = FALSE, error = FALSE}
# loading the necessary libraries
library(tidyverse)
library(ggplot2)
library(rio)
library(stringr)
library(RColorBrewer)
```

# Teaching

```{r}
teaching <- data.frame(rating = 1:6,
                       large_enrollment = c(304, 236, 169, 71, 34, 40),
                       upgrade_tech = c(163, 201, 209, 147, 100, 35),
                       mentoring = c(236, 238, 242, 128, 71, 40),
                       three_year_schedule = c(63, 116, 228, 184, 202, 62),
                       evidence_based_evaluations = c(275, 229, 167, 87, 63, 34),
                       course_release = c(133, 208, 239, 109, 127, 39),
                       incedntives_mentoring = c(200, 227, 202, 103, 81, 42),
                       distribute_workloads = c(488, 180, 97, 32, 30, 28))
```

```{r}
ggplot() + 
  geom_col(data = teaching, aes(x = rating, y = large_enrollment), fill = "orange", alpha = .5) +
  geom_col(data = teaching, aes(x = rating, y = upgrade_tech), fill = "blue", alpha = .5)
```



```{r}
ggplot(data.frame(x = rnorm(100)), aes(x)) +
  geom_density() +
  geom_function(fun = dnorm, colour = "red")
```

# Alexandra and I got the Same Results, so Using Hers <3

```{r}
#update_tech from alexandra data
update_tech <- data.frame(update_tech =1:6,
                             n = c(163, 201, 209, 147, 100, 35))

#pie chart for update_tech
pie(update_tech$n, col = c("#ff4e50", "#fc913a", "#f9d62e", "#eae374",  "#e2f4c7", "#fcfdf9", border = "white"), labels = c("1 - Highest", "2", "3", "4", "5 - Lowest", "No Answer"), main = "Upgrade technology for hybrid teaching")

```

```{r}
#mentoring from alexandra
mentoring <- data.frame(mentoring = 1:6,
                       n = c(136, 238, 242, 128, 71, 40))

#pie chart for mentoring
pie(mentoring$n, col = c("#ff4e50", "#fc913a", "#f9d62e", "#eae374",  "#e2f4c7", "#fcfdf9", border = "white"), labels = c("1 - Highest", "2", "3", "4", "5 - Lowest", "No Answer"), main = "Mentoring opportunities in competency-based training")

ggplot(data = mentoring, aes(x = mentoring, y = n)) + 
  geom_col(fill = c("#ff4e50", "#fc913a", "#f9d62e", "#eae374",  "#e2f4c7", "#fcfdf9"), col = "black") +
  theme_bw() +
  scale_x_continuous() +
  labs(title = "Mentoring Opportunities in Competency-Based Training") +
  xlab("Scale") +
  ylab("Count")

```



